### ISSUE TITLE
GAE-DAS什么时候开源

### ISSUE THREAD

**Issue by yetingrong** [wanghongfei/gae#1]
不错的项目，帮助很大，谢谢

**Comment by wanghongfei** [comment]
你好，首先感谢你的关注！

GAE这块目前只支持从文件中读取索引，后续要支持kafka，这样就不需通过让DAS跟GAE共享目录来实现索引文件的创建、加载了

DAS这块也要同时支持将索引写入文件和kafka两种方式，下班时间在做，应该这个月结束之前就可以传上来了
